name: docker_process
description: Access wrapper to interact with a docker container like a process.
version: 1.3.0
homepage: https://github.com/isoos/docker_process

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.0

dev_dependencies:
  pedantic: ^1.0.0
  postgres: ^2.3.0-0
  test: ^1.0.0
