name: docker_process
description: Access wrapper to interact with a docker container like a process.
version: 1.0.0
homepage: https://github.com/isoos/docker_process
author: Istvan Soos <istvan.soos@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  logging: ^0.11.0
  meta: ^1.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
